version: '3.8'
services:
  db:
    image: cockroachdb/cockroach:v21.2.16
    ports:
      - 8080:8080
      - 26257:26257
    restart: unless-stopped
    command: start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=localhost
