service: trakerapp

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  profile: trakerapp
  region: us-east-1
  architecture: arm64
  versionFunctions: false
  tags:
    Project: TrakerApp
    Environment: ${self:provider.stage}
  stackTags:
    Project: ${self:provider.tags.Project}
    Environment: ${self:provider.tags.Environment}
  environment:
    TRACKINGS_TABLE: ${self:service}-${self:provider.stage}-trackings
    OCCURRENCES_TABLE: ${self:service}-${self:provider.stage}-occurrences
  httpApi:
    cors: true

custom:
  webpack:
    webpackConfig: 'webpack.config.cjs' # Name of webpack configuration file
    # includeModules: false
    packager: 'yarn' # Packager that will be used to package your external modules
    excludeFiles: services/**/*.test.js # Provide a glob for files to ignore

plugins:
  - serverless-webpack

package:
  individually: true

resources:
  - ${file(./infra/dynamodb-trackings-table.yml)}
  - ${file(./infra/dynamodb-occurrences-table.yml)}
  - ${file(./infra/traker-lambda-dynamodb-reader-role.yml)}
  - ${file(./infra/traker-lambda-dynamodb-writter-role.yml)}
  - ${file(./infra/cognito-user-pool.yml)}

functions:
  # TRACKINGS API
  - ${file(services/v1/trackings-api/src/create/function.yml)}
  - ${file(services/v1/trackings-api/src/list/function.yml)}
