useDotenv: true

service: trakerapp

frameworkVersion: "3"

custom:
  webpack:
    webpackConfig: "webpack.config.cjs" # Name of webpack configuration file
    # includeModules: false
    packager: "yarn" # Packager that will be used to package your external modules
    excludeFiles: services/**/*.test.js # Provide a glob for files to ignore

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  profile: trakerapp
  region: us-east-1
  architecture: arm64
  versionFunctions: false
  tags:
    Project: TrakerApp
    Environment: ${self:provider.stage}
  stackTags:
    Project: ${self:provider.tags.Project}
    Environment: ${self:provider.tags.Environment}
  environment:
    STAGE: ${self:provider.stage}
    TRAKER_ENV: ${self:provider.stage}
    REGION: ${self:provider.region}
    DATABASE_URL: ${env:DATABASE_URL}
    LAMBDA_EXECUTION_ROLE_NAME: trakerapp-infra-${self:provider.stage}-execution-role
    LAMBDA_EXECUTION_ROLE_NAME_ARN: "arn:aws:iam::${aws:accountId}:role/${self:provider.environment.LAMBDA_EXECUTION_ROLE_NAME}"
  httpApi:
    cors: true
    authorizers:
      userAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_POOL_ID}
        audience:
          - ${env:COGNITO_CLIENT_ID}
plugins:
  - serverless-webpack

package:
  individually: true

functions:
  # TRACKINGS API
  - ${file(services/v1/trackings-api/create/function.yml)}
  - ${file(services/v1/trackings-api/get/function.yml)}
  - ${file(services/v1/trackings-api/list/function.yml)}
  - ${file(services/v1/trackings-api/occurrences/function.yml)}
  - ${file(services/v1/trackings-api/remove-occurrence/function.yml)}
  - ${file(services/v1/trackings-api/track/function.yml)}
  - ${file(services/v1/trackings-api/update/function.yml)}
