service: trakerapp-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  profile: trakerapp
  architecture: arm64
  versionFunctions: false

functions:
  hello:
    handler: src/functions/handler.hello
    events:
        - httpApi:
            method: GET
            path: /hello/yes
