service: trakerapp

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  profile: trakerapp
  region: us-east-1
  architecture: arm64
  versionFunctions: false
  tags:
    Project: TrakerApp
    Environment: ${self:provider.stage}
  stackTags:
    Project: TrakerApp
    Environment: ${self:provider.stage}
  httpApi:
    cors: true

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!*/**"

resources:
  - ${file(./infra/dynamodb-trackings-table.yml)}
  - ${file(./infra/traker-lambda-trackings-reader-role.yml)}
  - ${file(./infra/traker-lambda-trackings-writter-role.yml)}
  - ${file(./infra/cognito-user-pool.yml)}

functions:
  # TRACKINGS API
  - ${file(services/v1/trackings-api/src/create/function.yml)}
  - ${file(services/v1/trackings-api/src/list/function.yml)}
