Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service}-user-pool-${self:provider.stage}
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: true
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 6
      AutoVerifiedAttributes: ["email"]
  UserClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service}-user-pool-client-${self:provider.stage}
      # GenerateSecret: false
      UserPoolId: { Ref: UserPool }
      # AccessTokenValidity: 5
      # IdTokenValidity: 5
