Resources:
  TrackingsTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain # TODO: FOR PROD UNCOMMENT ME
    Properties:
      TableName: ${self:service}-${self:provider.stage}-trackings
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
