Resources:
  TrackingsTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain # TODO: FOR PROD UNCOMMENT ME
    Properties:
      TableName: ${self:provider.environment.TRACKINGS_TABLE}
      AttributeDefinitions:
        - AttributeName: userId # Primary key
          AttributeType: S
        - AttributeName: trackingId # NOT INDEXED! JUST FOR FETCHING OCCURRENCES
          AttributeType: S
        - AttributeName: name # Sort key, to avoid duplicates
          AttributeType: S
        - AttributeName: lastOccurenceAt # last occurrence createdAt, showing on trackings list
          AttributeType: N
        # - AttributeName: createdAt # Just for reference, not required/used
        #   AttributeType: N
      KeySchema:
        -
          AttributeName: userId
          KeyType: HASH
        -
          AttributeName: trackingId
          KeyType: RANGE
      LocalSecondaryIndexes:
        -
          IndexName: "lastOccurenceAtIndex" # Basically for the query on homepage
          KeySchema:
            -
              AttributeName: userId
              KeyType: HASH
            -
              AttributeName: lastOccurenceAt
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - trackingId
              - name
        -
          IndexName: "nameIndex" # Basically for the query on homepage
          KeySchema:
            -
              AttributeName: userId
              KeyType: HASH
            -
              AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
