Resources:
  OccurrencesTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain # TODO: FOR PROD UNCOMMENT ME
    Properties:
      TableName: ${self:provider.environment.OCCURRENCES_TABLE}
      AttributeDefinitions:
        - AttributeName: trackingId # Primary key
          AttributeType: S
        - AttributeName: createdAt # Sort key, to avoid duplicates
          AttributeType: N
      KeySchema:
        -
          AttributeName: trackingId
          KeyType: HASH
        -
          AttributeName: createdAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
