useDotenv: true

service: trakerapp-infra
provider: ${file(../serverless.yml):provider}
frameworkVersion: ${file(../serverless.yml):frameworkVersion}

resources:
  - ${file(./traker-lambda-execution-role.yml)}
  - ${file(./cognito-user-pool.yml)}
