Resources:
  TrakerLambdaTrackingsReaderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-trackings-reader-role-${self:provider.stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: ${self:service}-trackings-reader-role-policy-${self:provider.stage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource:
                  Fn::GetAtt: [TrackingsTable, Arn]
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  Fn::GetAtt: [TrackingsTable, Arn]
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource:
                  Fn::GetAtt: [TrackingsTable, Arn]
